### ISSUE TITLE
Invoices and Ownership transition

### ISSUE THREAD

**Issue by travisjayday** [COVIDAnalytics/website#216]
Hey @galitLukin, did you see the emails from me and Shalene? Maybe you're not using your @mit.edu email anymore so I thought I'd try to reach out like this. It seems kinda urgent. If you didn't see my email please LMK and I'll share it with you somehow again.

**TL;DR** Shalene needs the July 13th invoice; I got the credit card info; we need to transfer ownership

Sorry that this is happening *now*, I wish Shalene had reached out to me earlier. I know you're probably busy with other things :-/

Best, 
Travis :)

**Comment by galitLukin** [comment]
Hey Travis,

I do not read my mit email. I’ll send you the info tomorrow morning first
thing. If I don’t, please call me at 18572531425.

Galit

**Comment by travisjayday** [comment]
Hey @galitLukin , should I call you today?

**Comment by galitLukin** [comment]
Hey, yes just call me whenever you'd like

**Comment by travisjayday** [comment]
Hey @galitLukin, I know you're probably busy but would you mind trying to transfer ownership to me on Heroku? Finally got the credit card straightened out and added it to my account, so it should work now. 

Could you also send me the invoice for Septembr (Shalane is onto me)? Sorry for the long transition but after this, I should be all set for good! Thanks for your help :)

Best, 

Travis
